version : '3'
services:
  apsi:
    build: ./php
    image: apsi_php:latest
    container_name: apsi
    hostname: "apsi"
    volumes:
      - ./apsi_mantap:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_apsi
  db_apsi:
    image: mariadb:10.2
    container_name: db_apsi
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db_apsi/data:/var/lib/mysql
      - ./db_apsi/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_apsi:
    build: ./nginx
    image: nginx_apsi:latest
    container_name: nginx_apsi
    hostname: "nginx_apsi"
    ports:
      - "81:80"
    volumes:
      - ./apsi_mantap:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apsi